repos:
  - repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
      - id: black
        args: [--line-length=100]
        exclude: 'third_party/|train/question-answering/how/run_qa.py'

  - repo: https://github.com/pycqa/flake8.git
    rev: 3.9.2
    hooks:
      - id: flake8
        additional_dependencies: ["flake8-docstrings==1.7.0", "flake8-bugbear==23.3.12", "flake8-comprehensions==3.14.0"]
        args: ["--max-line-length=100", "--docstring-convention=numpy", "--extend-ignore=E203"]
        exclude: 'third_party/|train/question-answering/how/run_qa.py'

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]
        exclude: 'third_party/|train/question-answering/how/run_qa.py'

  - repo: https://github.com/hadolint/hadolint.git
    rev: v2.8.0
    hooks:
      - id: hadolint-docker
        entry: hadolint/hadolint:v2.8.0 hadolint
        args: ["--ignore=DL3008", "--ignore=DL3013", "--ignore=DL3018", "--ignore=DL3059"]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: requirements-txt-fixer


  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 3.0.5
    hooks:
      - id: sqlfluff-fix
        additional_dependencies : ['dbt-bigquery==1.0.0', 'sqlfluff-templater-dbt']
        args: ["--dialect=bigquery", "--exclude-rules=RF05"]
        # Exclude RF05 rule because we need '${}' symbols for creating a terraform template

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v4.0.0-alpha.8" # Use the latest version of Prettier
    hooks:
      - id: prettier
        name: Prettier
        entry: prettier --write
        language: node
        types: [json, yaml]
        additional_dependencies: ["prettier@latest"]
