name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  # Run linting checks
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      # Checkout the source code repository
      - name: Check out source repository
        uses: actions/checkout@v3

      # Set up Python with the right version
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pre-commit==4.0.1

      # Run pre-commit hooks
      - name: Run linting with pre-commit
        run: |
          pre-commit run --all-files
